FROM python:3.10-slim

# Cài đặt Java JRE và procps (bắt buộc cho PySpark)
RUN apt-get update && \
    apt-get install -y default-jre procps && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY config/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ /app/src/

# Chạy Spark Streaming script
CMD ["python", "src/streaming_pipeline.py"]
