FROM python:3.10-slim

WORKDIR /app

# Chỉ copy requirements để cài đặt nhằm tận dụng cache docker
COPY config/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code và tài liệu
COPY src/ /app/src/
COPY index.html /app/index.html
COPY doc/ /app/doc/

# Chạy FastAPI thông qua Uvicorn
CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "80"]
